services:
  task-hub-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: task-hub-backend
    restart: unless-stopped
    network_mode: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://172.20.0.2/task_hub?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATA_REDIS_HOST: 172.20.0.1
      SPRING_DATA_REDIS_PORT: 6380
      SERVER_PORT: 8096

  task-hub-frontend:
    image: nginx:alpine
    container_name: task-hub-frontend
    restart: unless-stopped
    ports:
      - "8097:80"
    volumes:
      - ../frontend/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - task-hub-backend
